// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID         int64       `json:"id"`
	DeviceName string      `json:"device_name"`
	RoomID     pgtype.Int8 `json:"room_id"`
	UserID     pgtype.Int8 `json:"user_id"`
}

type Reading struct {
	ID             int64          `json:"id"`
	ReadingWattage pgtype.Numeric `json:"reading_wattage"`
	ReadingHour    time.Time      `json:"reading_hour"`
	DeviceID       pgtype.Int8    `json:"device_id"`
}

type Room struct {
	ID       int64  `json:"id"`
	RoomName string `json:"room_name"`
}

type User struct {
	ID           int64  `json:"id"`
	UserEmail    string `json:"user_email"`
	UserPassword string `json:"user_password"`
}
